platform :ios, '6.0' 
pod 'SHNavigationControllerBlocks', :path => '../'
pod 'SHMessageUIBlocks', :git => "https://github.com/seivan/SHMessageUIBlocks.git"

target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod 'SHFastEnumerationProtocols', :git => "https://github.com/PodFactory/SHFastEnumerationProtocols"
  pod "KIF-next"
end
